#!/bin/bash
echo '=== huggingface reachability ==='
timeout 12 curl -sI https://huggingface.co 2>&1 | head -1 || echo 'HF TIMEOUT'
echo ''
echo '=== hf-mirror (china mirror) ==='
timeout 12 curl -sI https://hf-mirror.com 2>&1 | head -1 || echo 'HF-MIRROR TIMEOUT'
echo ''
echo '=== direct HF file HEAD (DiT-XL-2-256) ==='
timeout 15 curl -sI "https://huggingface.co/facebook/DiT-XL-2-256x256/resolve/main/DiT-XL-2-256x256.pt" 2>&1 | head -5 || echo 'HF FILE TIMEOUT'
echo ''
echo '=== try hf-mirror file HEAD ==='
timeout 15 curl -sI "https://hf-mirror.com/facebook/DiT-XL-2-256x256/resolve/main/DiT-XL-2-256x256.pt" 2>&1 | head -5 || echo 'MIRROR FILE TIMEOUT'